## Creating arrays 

In [3]:
import numpy as np

In [8]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)

In [10]:
my_array.shape

(4,)

In [12]:
my_array.dtype

dtype('int64')

In [14]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Using arrays and scalars

In [28]:
arr1 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])

In [30]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [32]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [37]:
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

## Indexing array

In [40]:
arr = np.arange(0, 11)

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#### Set all elements of the array to specific value:

In [47]:
arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

#### Hard copying arrays:

In [51]:
arr2 = arr1.copy()
arr2

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

#### 2d arrays

In [62]:
arr2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [63]:
arr2d[1] # second row

[4, 5, 6]

In [57]:
arr2d[0][1] # second element of the first row

2

In [65]:
arr2d[:2][1:] # two first rows, all columns except first one

[[4, 5, 6]]

#### Fancy indexing

In [87]:
fancy_array = np.zeros((10, 10))
fancy_array

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [90]:
array_length = fancy_array.shape[1]
for i in range(array_length):
    fancy_array[i] = i
fancy_array

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [91]:
# give me rows of index 2, 4, 6 and 8 from fancy_array
another_fancy = fancy_array[[2, 4, 6, 8]]
another_fancy

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

# Transposing arrays

In [5]:
arr = np.arange(50).reshape((10, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
#### transpose rows into columns
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

array([359, 358, 357, 356, 355, 354, 353, 352, 351, 350, 349, 348, 347,
       346, 345, 344, 343, 342, 341, 340, 339, 338, 337, 336, 335, 334,
       333, 332, 331, 330, 329, 328, 327, 326, 325, 324, 323, 322, 321,
       320, 319, 318, 317, 316, 315, 314, 313, 312, 311, 310, 309, 308,
       307, 306, 305, 304, 303, 302, 301, 300, 299, 298, 297, 296, 295,
       294, 293, 292, 291, 290, 289, 288, 287, 286, 285, 284, 283, 282,
       281, 280, 279, 278, 277, 276, 275, 274, 273, 272, 271, 270, 269,
       268, 267, 266, 265, 264, 263, 262, 261, 260, 259, 258, 257, 256,
       255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243,
       242, 241, 240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230,
       229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217,
       216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204,
       203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191,
       190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 17