## Creating arrays 

In [3]:
import numpy as np

In [8]:
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)

In [10]:
my_array.shape

(4,)

In [12]:
my_array.dtype

dtype('int64')

In [14]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Using arrays and scalars

In [28]:
arr1 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])

In [30]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [32]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [37]:
arr1 ** 2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

## Indexing array

In [40]:
arr = np.arange(0, 11)

In [41]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#### Set all elements of the array to specific value:

In [47]:
arr[:] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

#### Hard copying arrays:

In [51]:
arr2 = arr1.copy()
arr2

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

#### 2d arrays

In [62]:
arr2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [63]:
arr2d[1] # second row

[4, 5, 6]

In [57]:
arr2d[0][1] # second element of the first row

2

In [65]:
arr2d[:2][1:] # two first rows, all columns except first one

[[4, 5, 6]]

#### Fancy indexing

In [87]:
fancy_array = np.zeros((10, 10))
fancy_array

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [90]:
array_length = fancy_array.shape[1]
for i in range(array_length):
    fancy_array[i] = i
fancy_array

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [91]:
# give me rows of index 2, 4, 6 and 8 from fancy_array
another_fancy = fancy_array[[2, 4, 6, 8]]
another_fancy

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

## Transposing arrays

In [5]:
arr = np.arange(50).reshape((10, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
# transpose rows into columns
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

### Universal Array Functions

In [16]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# getting sqrt of every object in the array 
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [29]:
A = np.random.randn(10) # normal distribution of 10 random numbers 
A

array([-0.59926831, -0.83688659, -1.57859939, -0.44371228,  1.37790465,
       -1.04811108, -0.6179647 , -0.46440936,  0.44384853,  0.22292206])

In [30]:
B = np.random.randn(10) 
B

array([-0.22348834, -0.29942615,  0.67620115,  1.66765657,  0.84640641,
       -1.89785982, -1.71041032,  2.44659115, -0.28023725,  1.40368672])

In [24]:
# Adding each value of A to each one in B:
np.add(A, B) 

array([ -5.38498011e-01,   1.72648547e+00,   1.20897475e-03,
         1.29555703e+00,   1.92319696e+00,   3.15317156e+00,
        -6.09413693e-01,   2.47237410e+00,  -1.87461829e-01,
        -7.08631400e-01])

In [25]:
np.maximum(A, B)

array([ 0.49518399,  1.18164767,  0.33205352,  0.83557314,  1.33918051,
        2.08494305,  0.62063618,  1.32872704,  0.87887922, -0.32303524])

In [33]:
# all other functions: 
website = "https://docs.scipy.org/doc/numpy/reference/ufuncs.html"
import webbrowser

webbrowser.open(website)
    

True

## Array Processing

In [37]:
import matplotlib.pyplot as plt
%matplotlib inline

In [40]:
A = np.array([1, 2, 3, 4])
B = np.array([100, 200, 300, 400])
condition = np.array([True, True, False, False])

In [54]:
# merge these 3 lists above and select value of A list if the corresponding element in cond list is True 
# otherwise take the value from B list (B_val). Make a new list from this boolean operations
answer = [(A_val if cond else B_val) for A_val, B_val, cond in zip(A, B, condition)]
answer
    


[1, 2, 300, 400]

In [57]:
# The same can be done with numpy - where() method
answer2 = np.where(condition, A, B)
answer2

array([  1,   2, 300, 400])

In [64]:
from numpy.random import randn
arr = randn(5, 5)
arr

array([[ 1.33846605, -0.88015443,  0.61005817, -1.09027344,  1.70652379],
       [ 1.10222361, -0.85654828,  0.81756183, -0.03146477, -0.40211305],
       [ 0.11235458,  0.00515656, -1.59216884,  0.16170902,  1.66974898],
       [-0.96789421,  1.59100741,  0.22174807, -2.13806581, -0.56794494],
       [ 0.19242876,  0.16550397, -0.32577738, -0.29677896,  1.07875957]])

In [66]:
# if item is negative, set it as 0, otherwise take the item value
np.where(arr < 0, 0, arr)

array([[ 1.33846605,  0.        ,  0.61005817,  0.        ,  1.70652379],
       [ 1.10222361,  0.        ,  0.81756183,  0.        ,  0.        ],
       [ 0.11235458,  0.00515656,  0.        ,  0.16170902,  1.66974898],
       [ 0.        ,  1.59100741,  0.22174807,  0.        ,  0.        ],
       [ 0.19242876,  0.16550397,  0.        ,  0.        ,  1.07875957]])

In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
# sum all elements:
arr.sum()

45

In [80]:
# sum all elements with index 0
arr.sum(0)

array([12, 15, 18])

In [82]:
arr.mean()

5.0

In [83]:
# standard deviation
arr.std()

2.5819888974716112

In [85]:
# wariancja
arr.var()

6.666666666666667

In [90]:
# any of the element is True?
bool_arr = np.array([True, False, True])
bool_arr.any()

True

In [92]:
# all elements are True?
bool_arr.all()

False

In [97]:
# Sorting
random_arr = randn(5)
random_arr.sort()
random_arr

array([ 0.31260773,  0.90019416,  1.04662067,  1.46374586,  2.97957762])

In [102]:
# Show only unique elements from the array
countries = np.array(['France', 'Germany', 'USA', 'Russia', 'USA', 'Mexico', 'Germany'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'],
      dtype='<U7')

In [103]:
# show which elements from first list exist in the second one
np.in1d(['France', 'USA', 'Sweden'], countries)

array([ True,  True, False], dtype=bool)